Devrloper branch
Genesis-Front-End-School/clean-code-principes-Diana064 pull request #5
Opened 2023-04-17 08:25 UTC by Diana064

2023-04-17 10:37 UTC, xtadeushx commented on public/index.html
> +    <!--
видалити зайвий код та коменти

2023-04-17 10:37 UTC, xtadeushx commented on src/components/App.jsx
> +      <Route path="/" element={<ListCourses />} />
створити об'єкт шляхів та додавати конкретний шлях через властивість цього об'єкту  наприклад const APP_PATHS = {
ROOT= '/',
COURSES = '/courses'
}

2023-04-17 10:37 UTC, xtadeushx commented on src/components/CourseById/CourseById.jsx
> +  const defaultSrc =
винести в окремий файл наприклад constansts

2023-04-17 10:37 UTC, xtadeushx commented on src/components/CourseById/Lessons/LessonsData/LessonsData.jsx
> +  console.log(lesson);
видалити логери

2023-04-17 10:37 UTC, xtadeushx commented on src/components/Courses/Courses.jsx
> +  const [pageSize] = useState(10);
винести magic numbers в константи

2023-04-17 20:07 UTC, 37flwr commented on src/components/CourseById/Lessons/Lessons.jsx
> +      {containsLockedLessons && (lessons || []).length ? (
Наскільки я зрозумів, це зроблено для того, або виключити помилки коли lessons - undefined, і щоб не було TypeError при виклику undefined.length
Я б пропонував зробити це в вигляді lessons?.length, тому що з першого погляду не зрозуміло чому є порожній список та логічний операнд

2023-04-17 20:10 UTC, 37flwr commented on src/pages/CurrentCourse.jsx
> +            <>
Зайвий фрагмент

2023-04-18 06:15 UTC, xtadeushx approved these changes

2023-04-19 13:01 UTC, olesmarola requested changes

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/CourseById.jsx
> +  function progressTime(e) {
What is `e`?

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/CourseData/CourseData.jsx
> +    meta: { skills } = 'Missing skills',
Do you want to set a default value for the `meta`?

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/CourseData/CourseData.jsx
> +          )}
You can create a new component for this logic.

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/CourseData/CourseData.jsx
> +          )}
And reuse it.

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/InstructionVolume/InstructionVolume.jsx
> +        }
Could you create a function above for better readability?

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/Lessons/Lessons.jsx
> +  );
What's going on here? Too many ternary operators.

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/Lessons/LessonsData/LessonsData.jsx
> +    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
Move to const

2023-04-19 13:01 UTC, olesmarola commented on src/components/CourseById/Lessons/LessonsData/LessonsData.jsx
> +  function lessonTime(e) {
What is `e`?

2023-04-19 13:01 UTC, olesmarola commented on src/components/Courses/Courses.jsx
> +        <>
```suggestion

if (error) {
  return <>{error.message}</>
}

  return (
        <>
```

2023-04-19 13:01 UTC, olesmarola commented on src/components/Courses/CoursesItem/CoursesItem.jsx
> +    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
Move to const

2023-04-19 13:01 UTC, olesmarola commented on src/components/Courses/CoursesItem/CoursesItem.jsx
> +            : defaultSrc
move to variable above

2023-04-19 13:01 UTC, olesmarola commented on src/components/Courses/CoursesItem/CoursesItem.jsx
> +          )}
🤔

2023-04-19 13:01 UTC, olesmarola commented on src/components/VideoSpeed/VideoSpeed.jsx
> +  }, [playbackRate]);
```suggestion
  }, []);
```

2023-04-19 13:01 UTC, olesmarola commented on src/pages/ListCourses.jsx
> +    </>
```suggestion
      <Courses />
```

2023-04-25 08:49 UTC, merged